server.port=${PORT:8081}

wazuh.indexer-url=${WAZUH_INDEXER_URL:https://localhost:9200}
wazuh.username=${WAZUH_USERNAME:admin}
wazuh.password=${WAZUH_PASSWORD:senha}
wazuh.alert-index=${WAZUH_ALERT_INDEX:wazuh-alerts*}
wazuh.ignore-ssl=${WAZUH_IGNORE_SSL:true}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}